version: "3.9"
services:
  react-test:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
      - .:/app
  test:
    build:
      context: .
      dockerfile: Dockerfile.dev
    entrypoint: ["npm", "run", "test"]
    volumes:
      - /app/node_modules
      - .:/app